/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-30 06:08:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.uni.board.model.vo.Board;

public final class boardSelectDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/SEMI/SERVER_semi/pleaseCal_2/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1647444556028L));
    _jspx_dependants.put("jar:file:/C:/SEMI/SERVER_semi/pleaseCal_2/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/SEMI/SERVER_semi/pleaseCal_2/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.uni.board.model.vo.Board");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>게시글 상세 페이지</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	.outer {\n");
      out.write("		width:800px;\n");
      out.write("		height:500px;\n");
      out.write("		margin:auto;\n");
      out.write("		margin-top:30px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.outer>table, .outer>table tr>* {\n");
      out.write("		border:1px solid black;\n");
      out.write("		border-left: none;\n");
      out.write("		border-right: none;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.outer>table {\n");
      out.write("		width:800px;\n");
      out.write("		height:300px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.outer>table p {\n");
      out.write("		height:230px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.replyArea {\n");
      out.write("		width:800px;\n");
      out.write("		color: black;\n");
      out.write("		margin:auto;\n");
      out.write("		margin-top: 80px;\n");
      out.write("		margin-bottom:50px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.button {\n");
      out.write("		color: #fff;\n");
      out.write("  		border-radius: 5px;\n");
      out.write("  		padding: 5px 15px;\n");
      out.write("  		font-family: 'Lato', sans-serif;\n");
      out.write("  		font-weight: 500;\n");
      out.write("  		background: transparent;\n");
      out.write("  		cursor: pointer;\n");
      out.write("  		transition: all 0.3s ease;\n");
      out.write("  		position: relative;\n");
      out.write("  		display: inline-block;\n");
      out.write("   		box-shadow:	inset 2px 2px 2px 0px rgba(255,255,255,.5),\n");
      out.write("   					7px 7px 20px 0px rgba(0,0,0,.1),\n");
      out.write("   					4px 4px 5px 0px rgba(0,0,0,.1);\n");
      out.write("  		outline: none;\n");
      out.write("  		\n");
      out.write("		background: black;\n");
      out.write("	  	border: none;\n");
      out.write("	  	z-index: 1;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.button:after {\n");
      out.write("		position: absolute;\n");
      out.write("  		content: \"\";\n");
      out.write("  		width: 0;\n");
      out.write("  		height: 100%;\n");
      out.write("	  	top: 0;\n");
      out.write("	  	right: 0;\n");
      out.write("	  	z-index: -1;\n");
      out.write("	  	background-color: grey;\n");
      out.write("	  	border-radius: 5px;\n");
      out.write("   		box-shadow: inset 2px 2px 2px 0px rgba(255,255,255,.5),\n");
      out.write("   					7px 7px 20px 0px rgba(0,0,0,.1),\n");
      out.write("   					4px 4px 5px 0px rgba(0,0,0,.1);\n");
      out.write("  		transition: all 0.3s ease;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.button:hover {\n");
      out.write("		color: #fff;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.button:hover:after {\n");
      out.write("	  	left: 0;\n");
      out.write("	  	width: 100%;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.button:active {\n");
      out.write("	  	top: 2px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.detailArea {\n");
      out.write("		width:60%;\n");
      out.write("		margin:auto;\n");
      out.write("		margin-bottom: 20px;\n");
      out.write("		border:1px solid black;\n");
      out.write("		border-left: none;\n");
      out.write("		border-right: none;\n");
      out.write("		align: center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.detailArea th {\n");
      out.write("		background-color: lightgrey;\n");
      out.write("		text-align: center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.detailArea td {\n");
      out.write("		padding: 5px 5px 5px 10px;\n");
      out.write("		padding-left: 10px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#replyContent {\n");
      out.write("		margin: 0 10px 10px 10px;\n");
      out.write("		width: 600px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#replyList {\n");
      out.write("		border-left: none;\n");
      out.write("		border-right: none;\n");
      out.write("		width: 600px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#replyList tr:nth-child(2n+1) {\n");
      out.write("		background-color: lightgrey;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	#replyList tr:nth-child(2n) {\n");
      out.write("		background-color: ;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.replyContent {\n");
      out.write("		padding-left: 10px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.replyDate {\n");
      out.write("		padding-right: 10px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.rArea {\n");
      out.write("		margin-left: 84px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.replyDate {\n");
      out.write("		text-align: right;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	<!-- menu -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menu.jsp", out, false);
      out.write("\n");
      out.write("	\n");
      out.write("	<!-- header -->\n");
      out.write("   	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<div class=\"outer\">\n");
      out.write("		<br>\n");
      out.write("		\n");
      out.write("		<h2 align=\"center\">내가 작성한 게시글</h2>\n");
      out.write("		<br>\n");
      out.write("		\n");
      out.write("		<table align=\"center\" class=\"detailArea\">\n");
      out.write("			<tr>\n");
      out.write("				<th width=\"80px\">분야</th>\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>작성자</th>\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardWriter}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("				<th width=\"80px\">작성일</th>\n");
      out.write("				<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.createDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>내용</th>\n");
      out.write("				<td colspan=\"3\">\n");
      out.write("					<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("				</td>\n");
      out.write("			</tr>\n");
      out.write("			<tr>\n");
      out.write("				<th>첨부파일</th>\n");
      out.write("				<td colspan=\"3\">\n");
      out.write("					");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("						");
            out.write("\n");
            out.write("						");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /views/board/boardSelectDetailView.jsp(192,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty at}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("							");
                  out.write("\n");
                  out.write("							<a download=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${at.originName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\" href=\"");
                  out.print(request.getContextPath());
                  out.write("/resources/board_upfiles/");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${at.changeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write('"');
                  out.write('>');
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${at.originName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</a>\n");
                  out.write("						");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\n");
            out.write("						");
            out.write("\n");
            out.write("						");
            if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\n");
      out.write("				</td> \n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		<br>\n");
      out.write("		\n");
      out.write("		<div class=\"btns\" align=\"center\">\n");
      out.write("			<button class=\"button\" type=\"button\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/boardSelectList.do?currentPage=1';\">목록으로</button>\n");
      out.write("			");
      out.write("\n");
      out.write("			");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /views/board/boardSelectDetailView.jsp(209,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.loginUser && sessionScope.loginUser.getUserId() == b.boardWriter\n							|| !empty sessionScope.loginUser && sessionScope.loginUser.userId == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("				<button class=\"button\" type=\"submit\" onclick=\"location.href='");
            out.print(request.getContextPath());
            out.write("/boardSelectUpdateForm.do?bno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\">수정하기</button>\n");
            out.write("				<button class=\"button\" type=\"button\" onclick=\"deleteBoard();\">삭제하기</button>\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<form action=\"\" id=\"postForm\" method=\"post\">\n");
      out.write("			");
      out.write("\n");
      out.write("			<input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("		</form>\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		\n");
      out.write("		// 삭제 버튼 클릭 시\n");
      out.write("		function deleteBoard(){\n");
      out.write("			// 게시글 번호 변수에 담기\n");
      out.write("			let bno = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("			// 실행할 url\n");
      out.write("			let url = \"");
      out.print(request.getContextPath());
      out.write("/boardDeletePwdCheck.do?bno=\"+bno;\n");
      out.write("			// 팝업 이름\n");
      out.write("			let name = \"boardPwdCheckPopup\";\n");
      out.write("			// 팝업 속성\n");
      out.write("			let option = \"width = 500, height = 300, top = 50%, left = 50%, location = no\"\n");
      out.write("			// 위 세 가지는 필수 항목이며 이름은 없는 경우 \"\" 으로 대체 가능\n");
      out.write("			open(url, name, option);\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	</script>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<div class=\"replyArea\">\n");
      out.write("		<!-- 댓글 작성하는 div -->\n");
      out.write("		<table class=\"replyTable\" align=\"center\">\n");
      out.write("			<tr>\n");
      out.write("				<th>댓글작성</th>\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</tr>\n");
      out.write("		</table>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<!-- 댓글 리스트들 보여주는 div -->\n");
      out.write("		<div id=\"replyListArea\">\n");
      out.write("			<table id=\"replyList\" class=\"rArea\">\n");
      out.write("				<!-- <tr>\n");
      out.write("					<td width=\"100px\">admin</td>\n");
      out.write("					<td width=\"330px\">댓글작성내용</td>\n");
      out.write("					<td width=\"150px\">2020년 1월 23일</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"100px\">user01</td>\n");
      out.write("					<td width=\"330px\">댓글작성내용</td>\n");
      out.write("					<td width=\"150px\">2020년 1월 22일</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<td width=\"100px\">test01</td>\n");
      out.write("					<td width=\"330px\">댓글작성내용</td>\n");
      out.write("					<td width=\"150px\">2020년 1월 20일</td>\n");
      out.write("				</tr> -->\n");
      out.write("			</table>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		\n");
      out.write("		// 댓글 입력\n");
      out.write("		$(function() {\n");
      out.write("			\n");
      out.write("			selectReplyList(); // 입력하기 전에 댓글 리스트 출력하는 함수 먼저 실행\n");
      out.write("			\n");
      out.write("			$(\"#addReply\").click(function() {\n");
      out.write("				var content = $(\"#replyContent\").val(); // 댓글 내용\n");
      out.write("				var bno = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; // 게시글 번호\n");
      out.write("				\n");
      out.write("				$.ajax({\n");
      out.write("					url: \"replyInsert.do\", // 댓글 입력 서블릿으로 연결\n");
      out.write("					\n");
      out.write("					type: \"post\", // servlet에서 인코딩 먼저\n");
      out.write("					\n");
      out.write("					// servlet 변수명 : jsp 변수명\n");
      out.write("					data: {\n");
      out.write("							content : content,\n");
      out.write("							bno : bno\n");
      out.write("					},\n");
      out.write("					\n");
      out.write("					success: function(status){\n");
      out.write("						if(status ==\"success\"){ // 성공적으로 입력되면 (넘겨 받은 문자가 success 이면)\n");
      out.write("							selectReplyList(); // 리스트 조회해서 실시간으로 바뀌도록\n");
      out.write("							$(\"#replyContent\").val(\"\"); // 입력했으니 댓글 입력창 비워주기\n");
      out.write("						}\n");
      out.write("					},\n");
      out.write("					\n");
      out.write("					error: function(){\n");
      out.write("						console.log(\"ajax 통신 실패 - 댓글등록\");\n");
      out.write("					}\n");
      out.write("				})\n");
      out.write("				\n");
      out.write("			})\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		// 댓글 리스트 조회\n");
      out.write("		function selectReplyList() {\n");
      out.write("			\n");
      out.write("			$(\"#replyList\").empty(); // 조회할 때마다 비우고 다시 출력하도록\n");
      out.write("			\n");
      out.write("			$.ajax({\n");
      out.write("				\n");
      out.write("				url:\"replyList.do\",\n");
      out.write("				\n");
      out.write("				// 게시글 번호로 조회해서 가져올 것\n");
      out.write("				data: {bno:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("},\n");
      out.write("				\n");
      out.write("				type: \"get\",\n");
      out.write("				\n");
      out.write("				success: function(list){\n");
      out.write("					\n");
      out.write("					console.log(list);\n");
      out.write("					\n");
      out.write("					var value=\"\";\n");
      out.write("					\n");
      out.write("					for(var i in list){\n");
      out.write("						\n");
      out.write("						value += '<tr>'+\n");
      out.write("									'<td width=\"300px\" class=\"replyContent\">'+ list[i].replyContent+'</td>'+ \n");
      out.write("									'<td width=\"120px\" class=\"replyDate\">'+ list[i].createDate+'</td>'+ \n");
      out.write("								'</tr>';\n");
      out.write("					}\n");
      out.write("					\n");
      out.write("					$(\"#replyList\").html(value);\n");
      out.write("				},\n");
      out.write("				\n");
      out.write("				error: function(){\n");
      out.write("					console.log(\"ajax 통신실패 - 댓글조회\");\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("			})\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- footer-->\n");
      out.write("   	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							첨부파일이 없습니다.\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					");
          out.write("\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /views/board/boardSelectDetailView.jsp(254,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.loginUser && sessionScope.loginUser.userId == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<td><textarea rows=\"3\" cols=\"60\" id=\"replyContent\" style=\"resize:none;\"></textarea></td>\n");
          out.write("						<td><button class=\"button\" id=\"addReply\">댓글등록</button></td>	\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<td><textarea readonly rows=\"3\" cols=\"60\" id=\"replyContent\" style=\"resize:none;\">관리자만 사용 가능한 서비스입니다.</textarea></td>\n");
          out.write("						<td><button class=\"button\" disabled>댓글등록</button></td>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
