/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-24 01:45:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\" />\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write(" <meta name=\"description\" content=\"\" />\r\n");
      out.write(" <meta name=\"author\" content=\"\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body style=background:#f8f8f8>\r\n");
      out.write("\r\n");
      out.write("	<!-- popup -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "views/common/popup.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- menu -->\r\n");
      out.write("   	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "views/common/menu.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header-->\r\n");
      out.write("	<header class=\"bg-dark py-5\">\r\n");
      out.write("		<div class=\"container px-4 px-lg-5 my-5\">\r\n");
      out.write("			<div class=\"text-center text-white\">\r\n");
      out.write("				<h1 class=\"display-4 fw-bolder\">칼로리를 부탁해</h1>\r\n");
      out.write("				<p class=\"lead fw-normal text-white-50 mb-0\">With this shop hompeage template</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("   \r\n");
      out.write("   <section class=\"py-5\">\r\n");
      out.write("       <div class=\"container px-4 px-lg-5 mt-5\">\r\n");
      out.write("           <div class=\"row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center\" id=\"list\">\r\n");
      out.write("           		<!-- 대표상품 삽입 장소 -->\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   		$(function(){\r\n");
      out.write("   			\r\n");
      out.write("   			$.ajax({\r\n");
      out.write("   		   		url: \"topProduct.do\",\r\n");
      out.write("   		   		\r\n");
      out.write("   		   		type: \"get\",\r\n");
      out.write("   		   		\r\n");
      out.write("   		   		success:function(list){\r\n");
      out.write("   		   			\r\n");
      out.write("   		   			let value = \"\";\r\n");
      out.write("   		   			\r\n");
      out.write("   		   			for(var i in list){\r\n");
      out.write("   		   			  		   				\r\n");
      out.write("   		   			value += '<div class=\"col mb-5\">'+\r\n");
      out.write("							'<div class=\"card h-100\">'+\r\n");
      out.write("							'<a href=\"");
      out.print(request.getContextPath() );
      out.write("/detailProduct.do?no='+list[i].pId+'\"><img class=\"card-img-top\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/image/'+list[i].piName+'\" alt=\"상품이미지\" /></a>'+\r\n");
      out.write("		\r\n");
      out.write("							'<div class=\"card-body p-4\">'+\r\n");
      out.write("							'<div class=\"text-center\">'+\r\n");
      out.write("							'<h5 class=\"fw-bolder\">'+list[i].pName+'</h5>'+list[i].pPrice+' 원</div>'+\r\n");
      out.write("							'</div>'+\r\n");
      out.write("							'<div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">'+\r\n");
      out.write("							'<div class=\"text-center\"><a class=\"btn btn-outline-dark mt-auto\" href=\"");
      out.print(request.getContextPath() );
      out.write("/detailProduct.do?no='+list[i].pId+'\">상세정보</a></div>'+\r\n");
      out.write("							'</div></div></div>';\r\n");
      out.write("		                  \r\n");
      out.write("					}\r\n");
      out.write("					$(\"#list\").html(value);\r\n");
      out.write("   		   		},\r\n");
      out.write("   		   		\r\n");
      out.write("   		   		error:function(){\r\n");
      out.write("   		   			console.log(\"ajax통신실패\");\r\n");
      out.write("   		   		}\r\n");
      out.write("   	   		})\r\n");
      out.write("   		})\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("	<div class=\"container px-4 px-lg-6 mt-10\" id=\"reviewdiv\">\r\n");
      out.write("		<div class=\"owl-carousel owl-theme owl-loaded\">\r\n");
      out.write("			<div class=\"owl-stage-outer text-center\" >\r\n");
      out.write("		 		<h3>실제 구매한 고객님이 남긴</h3>\r\n");
      out.write("				<h4>REVIEW</h4>\r\n");
      out.write("			  	<div class=\"owl-stage\"  id=\"reviewList\">\r\n");
      out.write("				    <!-- 후기리스트 구역 -->  \r\n");
      out.write("			  	</div>\r\n");
      out.write("		  	</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		$(function(){\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("   		   		url: \"topReview.do\",\r\n");
      out.write("   		   		\r\n");
      out.write("   		   		type: \"get\",\r\n");
      out.write("   		   		\r\n");
      out.write("   		   		success:function(list){\r\n");
      out.write("   		   			\r\n");
      out.write("   		   			let value = \"\";\r\n");
      out.write("   		   			\r\n");
      out.write("   		   			for(var i in list){\r\n");
      out.write("   		   				\r\n");
      out.write("   		   			value += '<div class=\"owl-item card-body p-4\" id=\"title\">'+\r\n");
      out.write("					    		'<a id=\"a\" href=\"");
      out.print(request.getContextPath() );
      out.write("/detailProduct.do?no='+list[i].pId+'\"><img class=\"card-img-top\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/image/'+list[i].piName+'\" alt=\"상품이미지\" style=\"width: 200px; height:auto;\"/>'+\r\n");
      out.write("								'<br>'+\r\n");
      out.write("					    		'<h6 class=\"fw-bolder\" style=\"color:black\">'+list[i].rName+'</h6>'+\r\n");
      out.write("					    		'<br>'+\r\n");
      out.write("								'<div id=\"d\" class=\"card-footer p-4 pt-0 border-top-0 id=\"content\" style=\"background-color:#f8f8f8 \">'+list[i].rContent+'</div>'+\r\n");
      out.write("					   		'</div>';  				\r\n");
      out.write("\r\n");
      out.write("					}\r\n");
      out.write("   		   			\r\n");
      out.write("					$(\"#reviewList\").html(value);\r\n");
      out.write("   		   		},\r\n");
      out.write("   		   		\r\n");
      out.write("   		   		error:function(){\r\n");
      out.write("   		   			console.log(\"ajax통신실패\");\r\n");
      out.write("   		   		},\r\n");
      out.write("   		   		\r\n");
      out.write("	   		   	complete : function() {\r\n");
      out.write("	   		   		\r\n");
      out.write("		   		   	$(document).ready(function(){ // OWL Carousel API\r\n");
      out.write("		   		   		\r\n");
      out.write("		   			    let owl = $('.owl-carousel');\r\n");
      out.write("		   			    \r\n");
      out.write("		   			    owl.owlCarousel({\r\n");
      out.write("		   			        items:5,                 // 한번에 보여줄 아이템 수\r\n");
      out.write("		   			        loop:true,               // 반복여부\r\n");
      out.write("		   			        margin:15,               // 오른쪽 간격\r\n");
      out.write("		   			        autoplay:true,           // 자동재생 여부\r\n");
      out.write("		   			        autoplayTimeout:1800,    // 재생간격\r\n");
      out.write("		   			        autoplayHoverPause:true  // 마우스오버시 멈출지 여부\r\n");
      out.write("		   			    });    \r\n");
      out.write("		   			    \r\n");
      out.write("		   			    $('.customNextBtn').click(function() {\r\n");
      out.write("		   			        owl.trigger('next.owl.carousel');\r\n");
      out.write("		   			    })\r\n");
      out.write("		   			    \r\n");
      out.write("		   			    $('.customPrevBtn').click(function() {\r\n");
      out.write("		   			        owl.trigger('prev.owl.carousel', [300]);\r\n");
      out.write("		   			    })\r\n");
      out.write("		   			}); \r\n");
      out.write("	   		    }\r\n");
      out.write("\r\n");
      out.write("   	   		})\r\n");
      out.write("		\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <br><br><br><br>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <!-- Footer-->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
